# -*- coding: utf-8 -*-
"""Doc_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vE441HFkk8YbDoDp8zTJK82975-TDmwa
"""

!pip install langchain-community pypdf --quiet
!pip install requests==2.32.4 --quiet

import langchain_community

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/Generative AI Foundations in Python.pdf")
pdf_pages = loader.load()

pdf_pages[0]

"""## **Yt video loader**"""

!pip install yt_dlp --quiet
!pip install pydub --quiet
!pip install faster-whisper --quiet

from langchain_community.document_loaders.generic import GenericLoader
from langchain_community.document_loaders.parsers.audio import FasterWhisperParser
from langchain_community.document_loaders.blob_loaders.youtube_audio import YoutubeAudioLoader

url = "https://www.youtube.com/watch?v=aOQMmjoUglM&t=28s"

save_dir = "docs/youtube"
loader=GenericLoader(
    YoutubeAudioLoader([url],save_dir),
    FasterWhisperParser()
)
docs=loader.load()

docs[1]

docs[0]

len(docs)

combined_docs=pdf_pages+docs

len(combined_docs)

"""## **Chunking**"""

!pip install langchain-text-splitters --quiet

from langchain_text_splitters import RecursiveCharacterTextSplitter

chunk_size = 1024
chunk_overlap = 200

splitter = RecursiveCharacterTextSplitter(
    chunk_size=chunk_size,
    chunk_overlap=chunk_overlap
)

chunked_docs = splitter.split_documents(combined_docs)

len(chunked_docs)

chunked_docs[0]

from langchain_community.embeddings import HuggingFaceEmbeddings

all_minilm_embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

multilingual_embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

sen_1 = "I enjoy working on LLM models"
sen_2 = "I am working on RAG model"
sen_3 = "Before storing the chunked documents into vector database, we have to go through the process of embedding model"

emb_1 = all_minilm_embeddings.embed_query(sen_1)
emb_2 = all_minilm_embeddings.embed_query(sen_2)
emb_3 = all_minilm_embeddings.embed_query(sen_3)

import numpy as np

np.dot(emb_2,emb_3)

"""## **Vector** **DB** -> **Chroma**"""

!pip install langchain-chroma --quiet

!pip install chromadb --quiet

from langchain_community.vectorstores import Chroma

persist_directory = "/db/chroma/"

!pip install --upgrade --force-reinstall opentelemetry-api opentelemetry-sdk opentelemetry-semantic-conventions --quiet
!pip install langchain-chroma chromadb --quiet

!pip install --upgrade --force-reinstall opentelemetry-api opentelemetry-sdk opentelemetry-semantic-conventions
!pip install --upgrade chromadb langchain-chroma

from langchain_chroma import Chroma

persist_directory = "/db/chroma/"

vectordb = Chroma.from_documents(
    documents=chunked_docs,
    embedding=multilingual_embeddings,
    persist_directory=persist_directory
)

qn = "How to fine-tune a Generative AI model"

vectordb.similarity_search(qn, k=3)

vectordb.similarity_search_with_score(qn, k=3)

"""## **Retrieval**"""

vectordb.max_marginal_relevance_search(qn, k=3, fetch_k=10)

"""## **Metadata** **Filtering**"""

vectordb.similarity_search(qn, k=3, filter={"source":"/content/Generative AI Foundations in Python.pdf"})

"""## **Groq**"""

!pip install langchain-groq --quiet

import getpass
import os

if "GROQ_API_KEY" not in os.environ:
  os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your GROQ_API_KEY:")

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    max_tokens=250,
)

response = llm.invoke("write a poem about loneliness")

response.content

"""## **Prompt** **Engineering**"""

system_prompt = (
    "You are an assistant for question answering tasks. Use the following pieces of retrieved context to answer the question."
    "If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise."
    "Answer all questions in the best of your ability."
)

from langchain.messages import SystemMessage, HumanMessage, AIMessage

system_msg = [SystemMessage(content = system_prompt)]

question = "What is the future of generative AI applications?"

vectordb.similarity_search(question, k=3)

docs = vectordb.similarity_search_with_score(question, k=5)

import pandas as pd

_docs = pd.DataFrame(
    [(question, doc[0].page_content, doc[0].metadata.get("source"), doc[0].metadata.get('page'), doc[1]) for doc in docs],
    columns=['query', 'paragraph', 'document', 'page_number', 'relevant_score']
)

_docs

context = "\n\n".join(_docs['paragraph'])

context

human_msg = [HumanMessage(content=context+question)]

result = llm.invoke(system_msg + human_msg)

result.content

qn = "What is GPT?"

docss = vectordb.similarity_search_with_score(qn, k=5)

_docss = pd.DataFrame(
    [(question, doc[0].page_content, doc[0].metadata.get("source"), doc[0].metadata.get('page'), doc[1]) for doc in docss],
    columns=['query', 'paragraph', 'document', 'page_number', 'relevant_score']
)

contxt = "\n\n".join(_docs['paragraph'])
h_msg = [HumanMessage(content=contxt+qn)]
response = llm.invoke(system_msg + h_msg)

response.content

contxt

"""## **Memory**"""

!pip install langgraph --quiet

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import START, MessagesState, StateGraph

workflow = StateGraph(state_schema = MessagesState)

# Define the function that calls the model
def call_model(state: MessagesState):
  system_prompt = (
      "You are a helpful assistant. "
      "Answer all questions to the best of your ability."
  )
  messages = [SystemMessage (content=system_prompt)] + state ["messages"]
  response = llm.invoke(messages)
  return {"messages": response}

# Define the node and edge
workflow.add_node("model", call_model)
workflow.add_edge (START, "model")

# Add simple in-memory checkpointer
memory = MemorySaver()
app = workflow.compile(checkpointer= memory)

app

app.invoke(
    {"messages": [HumanMessage(content="What is the future of generative AI applications?")]},
    config={"configurable": {"thread_id": "1"}},
)

app.invoke(
    {"messages": [HumanMessage(content="What did I ask you?")]},
    config={"configurable": {"thread_id": "1"}},
)